services:
  retroarch:
    image: kasmweb/retroarch:1.17.0-rolling-daily
    container_name: retroarch_1
    user: "0:0"
    command: ["/bin/bash","-lc","chown -R 1000:1000 /home/kasm-user && /dockerstartup/vnc_startup.sh --wait"]
    ports:
      - "6901:6901"
      - "5901:5901"
    restart: unless-stopped
    shm_size: "1g"
    environment:
      - TZ=America/Fortaleza
      - VNC_PW=retropassword
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "video"
      - "render"
    volumes:
      - ${APP_DATA_DIR}/data:/home/kasm-user